### ISSUE TITLE
Pre-release testing in Onsala

### ISSUE THREAD

**Issue by varenius** [nvi-inc/fsl10#6]
I am testing FS 10, and the instructions, in Onsala - before the actual release. I know this means I may notice things which are already planned on being fixed before the actual release. But I note them here regardless:

- Section "4.10.3. Setup RAID": Between step 3 and step 4, I have to press "continue" instead of Enter. Pressing "Enter" selects/deselects in the list. This may be due to that I am using the "graphical install mode". Same applies to 4.10.4 step 4, but in that section it also also says "to continue", so it is obvious that "continue" is the option we want. Perhaps add "to continue" also to 4.10.3?
- Section "5.7. Download the FS Linux 10 package selections", the line `git checkout v1` fails. I assume I should stay on branch "master"?
- Section "6.4. Download the Field System" I assume I should stay on branch master now for the testing?
- In "fsadapt": OSO is not using GPIB, serial or VScom. Therefore, I deselected all GPIB-related options (ad noted), as well as all other options on windows 2,3 (i.e. using "skip" on these screens). Perhaps worth noting, as already done for GPIB, which sections could be skipped for stations not using serial or VScom. (We only use ethernet).

Except for this, I found the instructions very clear - very well done!

**Comment by jfhquick** [comment]
Thanks for the feedback.
As to your first point, section 4.10.3 has been harmonised with 4.10.4 and yet the behaviour difference around the enter key is due to using the graphical interface. 
For your second point, we now intend to keep the master branch tip up to date so no checkout will be needed.
As to installing the FS itself, you can play around with master but the first real release candidate will be 10.0..0-beta1.
For fsadapt, you should have done most of the steps in window 2 -- the installation notes have been clarified as to what to do when you don't intend to use the serial ports.  You will need to rerun fsadapt and perform the necessary steps to end up with a stock FSL10 installation.
